name: Hello World CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Step 3 - Build with mvn
        run: mvn -B package
        working-directory: ./Q2

      - name: Step 4 - Upload the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts 
          path: ./Q2/target/*.jar
          retention-days: 7
